# fly.toml file generated for job-send-email on 2023-04-02T11:33:18-05:00

app = "job-send-email"
kill_signal = "SIGINT"
kill_timeout = 5
primary_region = "scl"

[[services]]
  protocol = "tcp"
  internal_port = 8080
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20
